### ISSUE TITLE
[bug] Link to heading not working in pdf

### ISSUE THREAD

**Issue by Postur** [manuth/MarkdownConverter#103]
test.md

```
# Heading 1

[[toc]]

## Heading 1.1

## heading-to-link-to

text

## some other place

[Htlt](#heading-to-link-to)

```

in the pdf it looks like a link ( blue text ) but is not clickable.

in the html, if opened in a browser, the link works fine

links in the toc work on both.

Love the extension btw.

**Comment by manuth** [comment]
Hello, @Postur 
Thank you for your interest in MarkdownConverter

Sadly I couldn't reproduce the error.

I created a new file `test.md` with the following content:
```md
# Heading 1

[[toc]]

## Heading 1.1

## heading-to-link-to

text

## some other place

[Htlt](#heading-to-link-to)
```

Then, I created a PDF using the `Markdown: Convert Document` command.
As a result, I get a PDF document with all links working.

Make sure you have Markdown Converter v4.0.3 installed.

Also, you might want to post another example of a document with malfunctioning links.

Thanks for your interest in MarkdownConverter and thanks a lot for your appreciation ✨

**Comment by Postur** [comment]
[test.pdf](https://github.com/manuth/MarkdownConverter/files/7260518/test.pdf)
[test.md](https://github.com/manuth/MarkdownConverter/files/7260521/test.MD)


I still get the error.

I tried the pdf in edge and in foxit-reader. neither work.

**Comment by manuth** [comment]
This is what I get when converting a PDF
[test.pdf](https://github.com/manuth/MarkdownConverter/files/7260712/test.pdf)

Make sure that `markdownConverter.ChromiumExecutablePath` is **not** set.

What operating system are you working on?
I'm using Windows 10.

**Comment by Postur** [comment]
![image](https://user-images.githubusercontent.com/70761742/135488213-50fab104-1fb4-47f2-8934-0fb91a5da44d.png)

I do not have an executable path set.

I am running windows 10

did my pdf work for you?

your pdf works for me...

this is some weird bug, i'll reset my settings, and try again:

**Comment by manuth** [comment]
Your PDF isn't working for me either.
Sadly I can't tell what's causing the link to be removed.

I'm using a Windows 10 machine, too.
You might want to try to set the `ChromiumExecutablePath` to a local Chrome or MS Edge installation (or any other chromium) to see whether the problem is caused by MarkdownConverter's local copy of chromium.

**Comment by Postur** [comment]
Reset my settings and it works!

when I change the setting
from 
``` json
"markdownConverter.ConversionType": ["PDF"],
```
to
``` json
"markdownConverter.ConversionType": ["PDF", "HTML"],
```
It does not work

**Comment by manuth** [comment]
> Reset my settings and it works!
> 
> when I change the setting from
> 
> ```json
> "markdownConverter.ConversionType": ["PDF"],
> ```
> 
> to
> 
> ```json
> "markdownConverter.ConversionType": ["PDF", "HTML"],
> ```
> 
> It does not work

Thanks a lot for the effort!
I'll have a look into this asap.

**Comment by Postur** [comment]
Thank you!

**Comment by Postur** [comment]
fixed with https://github.com/manuth/MarkdownConverter/commit/463676402844da5e4e6ddc7139f191870785fdb3
