### ISSUE TITLE
[New feature request] Auto-complete links

### ISSUE THREAD

**Issue by Postur** [manuth/MarkdownConverter#107]
Suggest existing headings when making links.
``` markdown
#head1

## head 2

[link](#h)
```

should suggest head1 and head-2

``` markdown
#head1

## head 2

![image]()
```
should suggest images in workspace.

preferably with the build in vscode suggestions.

especially useful since special characters in headings get converted to non-special characters in the <h> id. 

valid link:
``` markdown
# krøv

[Krøv](#krov)
```
``` html
<h> id="krov"
```

Invalid link:
``` markdown
# krøv

[Krøv](#krøv)
```
``` html
<h> id="krov"
```

alternatively allow special charecters in ```<h> id```

**Comment by manuth** [comment]
Hello @Postur
Thanks for showing interest in MarkdownConverter once more.
Messing around with the IntelliSense of vscode isn't the goal of this extension.

However, I could try to get it to create the same slugs like vscode does here: https://github.com/microsoft/vscode/blob/0798d13f10b193df0297e301affe761b90a8bfa9/extensions/markdown-language-features/src/slugify.ts

Sadly, there is no npm-package that creates correct looking slugs so I'll have to hard-code this into my extension.

Expect this in the upcoming patch-releae.
