### ISSUE TITLE
Shortcut to open Command Pallet in VSC

### ISSUE THREAD

**Issue by WesleyGoncalves** [manuth/MarkdownConverter#11]
Hi, the right keyboard shortcut to open command pallet is `Ctrl` + `Shift` + `P` instead of the `Ctrl`+`P` (in [README](https://github.com/manuth/MarkdownConverter/blob/master/README.md) file) which is used to quickly search and open a file (Quick Open). 
Reference:  https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette

Thanks for the plugin. Helped me a lot.

**Comment by manuth** [comment]
Hello
Thanks for opening the issue - I never noticed this error in my docs.
I'll correct this asap!

Stay tuned
Manu

**Comment by WesleyGoncalves** [comment]
If you want I can make a PR and you just review it. 
Thanks for the quick response.
