### ISSUE TITLE
MarkdownConverter couldn't build the propper version of PhantomJS

### ISSUE THREAD

**Issue by chesucr** [manuth/MarkdownConverter#12]
I am getting this error when I try to print a markdown file into a PDF file:

    MarkdownConverter couldn't build the propper version of PhantomJS. Restart VSCode in order to try it again.

And this is appearing on the debug console:

    [manuth.markdown-converter]
    e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43

    mainThreadExtensionService.ts:44 Error: 
        at /[...]/.vscode/extensions/manuth.markdown-converter-0.0.11/out/src/extension.js:50:27
        at ChildProcess.exithandler (child_process.js:224:5)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:194:7)
        at maybeClose (internal/child_process.js:899:16)
        at Socket.<anonymous> (internal/child_process.js:342:11)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:191:7)
        at Pipe._handle.close [as _onclose] (net.js:510:12)

# VSCode Version

```
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T16:04:33.747Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

# SO Version
Ubuntu 16.04.4 LTS

**Comment by chesucr** [comment]
Thank you for the quick response. It worked with

    npm install
    npm install phantomjs-prebuilt

I had to force the installation of phantomjs for some reason

**Comment by manuth** [comment]
I decided to use puppeteer rather than PhantomJS which doesn't have such issues.
I'll need to implement some more stuff like update-messages, settings etc. which I think will take some months.

Some first steps have been taken in 3512cb43afef660119484c1b130a9d5f742d6e7a and f0e0a91c762259220c7f7a8eb28df9698dd3a177.

Stay tuned!
