### ISSUE TITLE
Word wrap is not occurring at the end of the page, and words run off the side

### ISSUE THREAD

**Issue by DavidS-BDO** [manuth/MarkdownConverter#120]
Markdown is the following:

I have tried editing many of the settings including: margins  and page format, but none of them seem to do the trick.

```
[Visual Studio Code](https://code.visualstudio.com/), also known as VS Code, is a lightweight editor that works on Windows, Linux, 
and Mac. It includes git integration, and support for extensions. also known as VS Code, is a lightweight editor that works on 
Windows, Linux, and Mac. It includes git integration, and support for extensions.
```
which presents this:

![image](https://user-images.githubusercontent.com/60764631/138780585-76f3e670-b904-4539-a924-6197f7b55be6.png)

**Comment by manuth** [comment]
Hello @DavidS-BDO
Sorry for the late response.

Could you please send me the full document?
Also - do you have any custom settings or css-styles configured?

Thanks for using MarkdownConverter

**Comment by manuth** [comment]
In order to keep my issues board clean, I'll close this issue now.
Please feel free to reopen this issue if your problem persists.
