### ISSUE TITLE
Generated PDF uses unreadable/unprintable colors

### ISSUE THREAD

**Issue by sba923** [manuth/MarkdownConverter#18]
This example should speak for itself: the "light grey text over slightly lighter grey" almost can't be read, either on-screen or on a printout.

[test2.zip](https://github.com/manuth/MarkdownConverter/files/2177296/test2.zip)
[test2.pdf](https://github.com/manuth/MarkdownConverter/files/2177297/test2.pdf)
![test2 pdf as displayed by acrobat reader dc](https://user-images.githubusercontent.com/12860484/42465870-c1190a0c-839c-11e8-9aec-4d402d24677b.png)

**Comment by manuth** [comment]
I could find the cause of the issue.
I forgot to add some expressions to the stylesheet but that's done for now.

I'll fix the stylesheet and release a new version so that code-blocks are looking fancy again.

Thank you for using MarkdownConverter!
