### ISSUE TITLE
Executing PhantomJS on a Linux causes errors

### ISSUE THREAD

**Issue by manuth** [manuth/MarkdownConverter#2]
Converting MarkDown to any format but HTML causes following error:

```
Error: spawnSync /home/w/.vscode/extensions/manuth.markdown-converter-0.0.6/node_modules/phantomjs-prebuilt/lib/phantom\bin\phantomjs.exe ENOENT
Open FileClose
InfoSuccessfully wrote the HTML-file to "/home/w/wWorks/buresh_ru/zDev-ib-ru/infoPravo/Law_3-includs/README.html".
```

**Comment by wBureshGitHub** [comment]
Hi, Manuel

Very good start!

It seems that everything is working fine, only the error message is displayed.
The problem has appeared on Linux, Debian, Stretch

Regards,
Vladimir

**Comment by manuth** [comment]
Hi Vladimir

I found the problem's source.
It's because PhantomJS inside my extension is built for Windows.
I'm just about to fix it by automatically building the propper version of PhantomJS when the extension's activated.
