### ISSUE TITLE
Customize the CSS file used when converting to HTML

### ISSUE THREAD

**Issue by Leedehai** [manuth/MarkdownConverter#3]
I figure it would be good idea to allow users to decide which CSS file they want to use when converting markdown to HTML, instead of just using the default CSS file provided by VSCode.
_____
By the way, very good tool! Many other converters convert my box-drawing characters (like the one below) to a bunch of gibberish, but your tool works fine :)
┌───┬───┬───┬───┬───┬───┐    
└───┴───┴───┴───┴───┴───┘

**Comment by manuth** [comment]
Hey Leedehai
This is possible by specifying the styles- or stylesheets-settings in your user-settings:
```json
{
    "markdownConverter.document": {
        "style": {
            "useSystemStyles": false,
            "styles": "body: { color: red !important; }",
            "styleSheets": [
                "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            ]
        }
    }
}
```

  - Use `useSystemStyles` to define whether to use the CSS-styles provided by Visual Studio.
  - Use `styles` in order to provide custom CSS-code
  - Use `styleSheets` to define a set of CSS-files to use.  
     This can either be an uri or a local path

Please have a look at the [Config-Section](https://github.com/manuth/MarkdownConverter/wiki/Config) in the MarkdownConverter-wiki.

Thanks for using MarkdownConverter

~Manu

**Comment by Leedehai** [comment]
Hi Manuel,
Thanks for your reply :)I checked the settings.json file, there is not an entry named "useSystemStyles" under "markdownConverter.document". The last entry under "markdownConverter.document" is "footer". I also searched in this json file, there is not a string that matches with "useSystemStyles".
FYI, I am using VSCode on macOS. I downloaded the tool a few hours ago..
		

		
	_____________________________

**Comment by manuth** [comment]
Hello Leedehai
The styles-node isn't provided in the default settings so you wouldn't be able to find it by using the search-bar in the configuration-editor.
However the auto-completion will suggest you the propper nodes automatically.

Keep in mind there is a `style`-node inside the `document`-node which contains settings like `template`, `styles`, `styleSheets`, `useSystemStyles` etc.

**Comment by Leedehai** [comment]
It works, thanks!
		

		
	





On Wed, Apr 26, 2017 at 1:47 AM -0700, "Manuel Thalmann" <notifications@github.com> wrote:












Hello Leedehai

The styles-node isn't provided in the default settings so you wouldn't be able to find it by using the search-bar in the configuration-editor.

However the auto-completion will suggest you the propper nodes automatically.


Keep in mind there is a style-node inside the document-node which contains settings like template, styles, styleSheets, useSystemStyles etc.

**Comment by manuth** [comment]
You're welcome!
If you have further questions feel free to open up a new issue.

Manu
