### ISSUE TITLE
Plantuml support

### ISSUE THREAD

**Issue by damgot** [manuth/MarkdownConverter#30]
Hello,

I would be nice if you can integrate plantuml. https://www.npmjs.com/package/markdown-it-plantuml

Regards

**Comment by damgot** [comment]
Hi @manuth 
Thanks for your answer.

It works perfectly. You can close the issue. Thanks for this solution.

Please, don't abandon markdownConverter, it is really the best pdf converter I found on the vscode market.

**Comment by manuth** [comment]
Do not worry, btw
I'm definitely not gonna stop developing MarkdownConverter.
I just suspended it for some time until I finished creating my website and some other tiny projects.

Thank you for using MarkdownConverter! 🎉

**Comment by damgot** [comment]
Hello,

Instead of creating a new "issue", I prefer asking you directly my question.

With markdown-converter, Is there a way to configure pdf header and footer
directly in my ".md" document or do I have to change it each time in my
setting.json ?

Many thanks and best regards.

Damien

Le jeu. 30 mai 2019 à 19:27, Manuel Thalmann <notifications@github.com> a
écrit :
