### ISSUE TITLE
[enhancement] : Add the option "break on single new line"

### ISSUE THREAD

**Issue by damgot** [manuth/MarkdownConverter#32]
It would be great to have the possibility to generate a line break if we have only a single newline in our .md document.

This option is available with markdown-it. 

So this could be done, I guess, only with a checkbox in the Markdown Converter settings, and checkbox value reported in file "src/MarkdownConverter/ConvertCommand.ts" line 172 :

```javascript
parser = new MarkdownIt({ 
                html: true, 
                breaks: (true or false depending the checkbox in settings), 
                highlight: (subject, language) =>```

**Comment by damgot** [comment]
Can be enabled directly in markdown-it integrated in vscode.
Settings/Extensions/Markdown/Markdown>Preview:Breaks

**Comment by manuth** [comment]
Awesome!
Thanks for your suggestion, though
I really depend on you guys' feedback and intentions, so I really appreciate it :smile:

Thanks for using Markdown Converter!
