### ISSUE TITLE
Links with non-ASCII characters works in HTML but not in PDF

### ISSUE THREAD

**Issue by damgot** [manuth/MarkdownConverter#33]
Both following examples will work when converting in HTML.

But only the first will work in PDF, link will be broken for the second.

```
[Ce test fonctionne](#Ce-test-fonctionne)

<a id="UnTestQuiFonctionne" name="Ce-test-fonctionne"></a>
It works

[Ce test n'a pas fonctionné](#Ce-test-na-pas-fonctionné)

<a id="UnTestQuiNeFonctionnePas" name="Ce-test-na-pas-fonctionné"></a>
It doesn't work
```

It's an issue when using French.

**Comment by manuth** [comment]
Hi @damgot 
Looks like an issue related to puppeteer.
I didn't perform any dependency-updates for quite a while. Maybe it's aready been fixed. I'll go and try to reproduce the issue asap!

**Comment by manuth** [comment]
I could verify that this issue even exists in Chrome.
I think, there's nothing I can do about this.

I'll leave this issue open, just in case some PDF-standards or chrome itself is being updated.

**Comment by manuth** [comment]
hello @damgot 
Things got pretty quiet around this project and I'm really sorry for this.
The most recent Chromium version now supports anchors and links containing non-ASCII characters and I'm looking forward to release the next major verison of MarkdownConverter soon.

Thanks for your patience

**Comment by damgot** [comment]
Hello, thanks for your Feedback.
No problem, your extension works pretty well. It's not a blocking "bug".

Thanks
