### ISSUE TITLE
Customize PDF header and footer ?

### ISSUE THREAD

**Issue by matiasbasilico** [manuth/MarkdownConverter#34]
Is there a possibility to change the header and footer generated by the pdfs?

Thanks for this great tool

**Comment by manuth** [comment]
Hi @matiasbasilico
Sorry for not answering - I totally missed your issue as I didn't really work on MarkdownConverter for quite a while.

You can adjust the header and footer by editing the `markdownConverter.Document.HeaderTemplate` and the `markdownConverter.Document.FooterTemplate`-option.

You can easily find these options in the settings editor by searching for `Header Template` or `Footer Template`.
