### ISSUE TITLE
command 'markdownConverter.Convert' not found

### ISSUE THREAD

**Issue by luoqining** [manuth/MarkdownConverter#35]
Version 2.0.0, When use command "Convert Document" ,but show "command 'markdownConverter.Convert' not found". 
BTW, v1.1.2 is OK.

**Comment by luoqining** [comment]
VS Code version is 1.37.1

**Comment by manuth** [comment]
I'll have a look at this issue as soon as possible!

**Comment by kostakis** [comment]
Yea i also had this issue at the latest version of VS code(July 2019 version 1.37)
Had to go back to previous version to have a temporary fix

**Comment by manuth** [comment]
I'm really sorry for you guys having trouble.
I removed the "puppeteer"-package from the dependency-tree by accident, which is a key dependency of MarkdownConverter.

I'll re-add the package and publish the new version as soon as I'm home.
Please be patient

Kind regards
Manu

**Comment by manuth** [comment]
@luoqining, @kostakis: I just released a fixed version of the extension which should be accessible in a few minutes.

Thanks for being patient!
