### ISSUE TITLE
MarkdownConverter 2.0.1 : Margins parameter as no Effect

### ISSUE THREAD

**Issue by damgot** [manuth/MarkdownConverter#36]
Settings "markdownConverter.Document.Paper.Margin": {
        "Top": "4cm",
        "Bottom": "3cm",
        "Left": "1cm",
        "Right": "1cm"
    },

as no effect on the rendered PDF.

**Comment by manuth** [comment]
Hi Damien

Thank you for reporting the issue, looks like my code has been incorrect for a very long time so I'm really glad to get this patched.
Please be patient.

**Comment by damgot** [comment]
Hello, a lot of thanks for your reactivity :)
