### ISSUE TITLE
MarkdownConverter 2.0.1 : Custom Header and footer are not working anymore

### ISSUE THREAD

**Issue by damgot** [manuth/MarkdownConverter#37]
When specify custom header and footer, nothing is displayed : 

Example : 
"markdownConverter.Document.FooterTemplate": "<div style=\"border-top: 1px solid #999999; width: 100%; margin-left: 1cm; margin-right: 1cm; margin-bottom: 0.5cm;\"><span style=\"float:left; margin-left: 0.5cm; margin-top: 0.2cm; color:#F0F0F0;\">Version: {{ version }} - {{ date }}</span><span style=\"float: right; margin-top: 0.2cm; margin-right: 0.5cm; color:#F0F0F0;\">page <span class=\"pageNumber\"></span>/<span class=\"totalPages\"></span></span></div>",

"markdownConverter.Document.HeaderFooterEnabled": true

No footer is rendered in the pdf

**Comment by damgot** [comment]
Maybe related to #36 (header and footer are maybe hidden)

**Comment by manuth** [comment]
Hello @damgot 
I just had a look at this issue and it's indeed related to #36 
Therefore I'm going to close this issue now.

Please refer to said issue to stay tuned!

Thanks for reporting the issue and for using MarkdownConverter :smile:
