### ISSUE TITLE
Convert command hanging on "Convert Document: Launching the page in chromium…"

### ISSUE THREAD

**Issue by damgot** [manuth/MarkdownConverter#42]
Convert command hanging on "Convert Document: Launching the page in chromium…"

In a debug session, I've the following error :
```
rejected promise not handled within 1 second: Error
extensionHostProcess.js:783
stack trace: Error: 
	at 9.n.Document.<anonymous> (c:\Users\Damgot\.vscode\extensions\manuth.markdown-converter-3.0.1\MarkdownConverter\lib\extension.js:1:20209)
	at Generator.next (<anonymous>)
	at o (c:\Users\Damgot\.vscode\extensions\manuth.markdown-converter-3.0.1\MarkdownConverter\lib\extension.js:1:17480)
```

chromium was installed successfully

**Comment by manuth** [comment]
Hello @damgot 
Are you sure you copied the whole stacktrace?
Thanks for reporting the issue

**Comment by manuth** [comment]
I can't reproduce the issue.
Could you please post some more information about the system you're running for me to set up a proper VM?
Also what command are you trying to execute?

**Comment by damgot** [comment]
Hello @manuth.

It's on a very new installation. I've installed VSCode + Markdown All In One, Plantuml, markdownlint, and markdownConverter.

I tried to convert a .md document with "Markdown: Convert Document" command. I had a pop-up to install chromium, select "Yes", download was successfull and then the pop-up stayed infinitely on "Convert Document: Launching the page in chromium…"

I try to restart VSCode, restart computer, Uninstall-reinstall MarkdownConverter (and downloand again chromium) but nothing works.

This short stack trace is all I have, sorry =S

My OS is Windows 10 Pro (10.0.18362) and the system is a x64. 
VSCode version is 1.38.1.

Thanks for help

**Comment by manuth** [comment]
Please try the debug-build I've just created:  
[markdown-converter-3.0.1.vsix.zip](https://github.com/manuth/MarkdownConverter/files/3653650/markdown-converter-3.0.1.vsix.zip)

Do you see any useful information in the stack trace?
You should get concrete line-numbers now.

**Comment by damgot** [comment]
It seems to be well installed because I saw command in the command palette, but I've the error : "command 'markdownConverter.Convert' not found" =S

**Comment by manuth** [comment]
Thank you, this helped me finding the issue.
Could you please go and try this new build?
[markdown-converter-3.0.1.vsix.zip](https://github.com/manuth/MarkdownConverter/files/3653911/markdown-converter-3.0.1.vsix.zip)

**Comment by damgot** [comment]
Ok now I've this : 
```
rejected promise not handled within 1 second: Error
extensionHostProcess.js:783
stack trace: Error: 
	at Document.<anonymous> (c:\Users\Damgot\.vscode\extensions\manuth.markdown-converter-3.0.1\MarkdownConverter\lib\System\Documents\Document.js:243:31)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\Damgot\.vscode\extensions\manuth.markdown-converter-3.0.1\MarkdownConverter\lib\System\Documents\Document.js:5:58)
```

**Comment by manuth** [comment]
Alright now we're getting to something.
I'll go try to find out what's goint wrong for you ^^

**Comment by damgot** [comment]
Ok I've found it...

As it was a new install, I've simply copy past the JSON settings... But the path of my stylesheet in this new install was not exactly the same than before.
With the correct path everything works fine.

The bug was on my side.
But for enhancement, a error pop-up like "Missing stylesheet" or something like that could be useful ^^

**Comment by damgot** [comment]
The problem was there :
```
for (let styleSheet of this.StyleSheets) {
                if (/.*:\/\//g.test(styleSheet) || !Path.isAbsolute(styleSheet)) {
                    styleCode += Dedent(`<link rel="stylesheet" type="text/css" href="${styleSheet}" />\n`);
                }
                else {
                    if (yield FileSystem.pathExists(styleSheet)) {
                        styleCode += "<style>" + (yield FileSystem.readFile(styleSheet)).toString() + "</style>\n";
                    }
                    else {
                        **throw new FileException_1.FileException(null, styleSheet);**
                    }
                }
            }
```

**Comment by manuth** [comment]
Well that's pretty strange anyway, I thought my exception-handling covers all possible exceptions-  I'll have a look at it asap.

But please don't blame me if it takes 2 days or 3 - I have a lot exams this week.

**Comment by damgot** [comment]
There is no problem.
My issue is solved, it works, take your time to look at this :).

Many thanks for helping me solve my problem :)

**Comment by manuth** [comment]
You're welcome mate 😄

**Comment by manuth** [comment]
Alright so I finally could find what's causing the error.
https://github.com/manuth/MarkdownConverter/blob/aea93de404d39570a4a83dc740486fc647672164/MarkdownConverter/src/Conversion/Converter.ts#L308-L323

The `async (request) => { }` portion of the code is not executed in a separate Promise-chain which causes this empty-looking stacktrace.

I could resolve this issue by moving the `this.Document.Render()` portion out of said `page.on("request")`-scope.

I'll publish another new release this evening.

**Comment by damgot** [comment]
Tested and approved :).

Thanks a lot
