### ISSUE TITLE
[Question/Enhancement] Using markdown extension stylesheet as markdownconverter stylesheet

### ISSUE THREAD

**Issue by damgot** [manuth/MarkdownConverter#43]
Hello,
I've created a small VSCode extension which add my own stylesheet to the VSCode markdown extension.

So I just have my css in my extension and in the package.json I just set : 

```
"contributes": {
"markdown.previewStyles": [
			"./my.css"
		]
	}
```

Is there a way to use this css as stylesheet for markdownConverter ?

Thanks a lot

**Comment by damgot** [comment]
I had not tested with leaving the "markdownConverter.Document.Design.StyleSheets" option empty.

It really works like a charm.

Many thanks for your help !
(And thanks for your work in this extension)

**Comment by manuth** [comment]
You're welcome!
Thanks for appreciating my work 😄
