### ISSUE TITLE
Stuck on "Convert Document: Scraping all files and resources…"

### ISSUE THREAD

**Issue by ViRb3** [manuth/MarkdownConverter#44]
Hello,

I am trying to use MarkdownConverter on the cloud using [code-server](https://github.com/cdr/code-server). I installed the needed dependencies (`libxss1 libgtk-3-0`), but now the extension is stuck on `"Convert Document: Scraping all files and resources…"`. Looking at Chrome in `top`, it doesn't take any CPU usage which suggests it is stuck. Is there any way to debug this?

Thanks!

**Comment by manuth** [comment]
Well as far as I read in the latest release notes of VSCode it is now possible to do remote debugging:
https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger

Is this here of any help for you by chance?

On a local environment you can debug this project in VSCode by opening the debug section and starting the "Launch Extension" option for starting a test-instance of VSCode or "Launch Tests" for running the mocha-tests.

Sadly I ain't going to work on any project but https://github.com/manuth/TypeScriptESLintPlugin cause school is causing a lot of headache lately.

I'll have a look at it as soon as I possible.
Thanks for using MarkdownConverter! :smile:

**Comment by ViRb3** [comment]
Seems to work just fine on code-server v3, the latest stable! I couldn't debug the extension in code-server as it seems to be unsupported, but I am happy that won't be needed anymore!
