### ISSUE TITLE
Change Company attribute

### ISSUE THREAD

**Issue by Jerem59** [manuth/MarkdownConverter#46]
Hi
good job for this extension
How change the company attribute value ?
How add new attribute ?
Possible to increase the content of the documentaion ?
Thx
Jerem

**Comment by manuth** [comment]
Hello
You can add new attributes using the `markdownConverter.Document.Attributes`-setting.

```
    "markdownConverter.Document.Attributes": {
        "Company": "Contosocom"
    }
```

I'm sorry for the lack of documentation but I'll work on it as soon as possible.
Kind regards
Manu

**Comment by manuth** [comment]
I'm closing this issue now as you didn't answer for quite a long time now.
I hope I could help you working with MarkdownConverter.

Feel free to open up a new issue whenever you find a bug or have a question about this project. ✨
