### ISSUE TITLE
Footer: Want File Modified Date

### ISSUE THREAD

**Issue by GGillan** [manuth/MarkdownConverter#54]
Thanks for an awesome extension!

I have to be careful keeping track of what version of a PDF I'm using. The default pulls CreationDate to put into the page footer. On Windows the creation date does not change with successive edits and saves while the modified date does change. Unfortunately, I have been unable to find how to get the extension to pull the modified date. I've tried many iterations of ModifyDate, ModificationDate, and so on. I also tried ChangeDate (found here https://docs.microsoft.com/en-us/windows/win32/adschema/a-mswmi-changedate).

Is CreationDate the only option supported, or have I simply not found the right syntax or option name?

Thanks,
George

**Comment by manuth** [comment]
Currently the `CreationDate`-attribute is loaded from the creation-date of the source-file as seen in this piece of code:
https://github.com/manuth/MarkdownConverter/blob/798676b874cf7cac39ca0bab55d707c0bd3e5891/src/System/Documents/Document.ts#L115-L124

I'm planning to release a new major version of MarkdownConverter quite soon.

I'll definitely include new attributes for covering your need in the upcoming version.
What do you think about `ModificationDate` for the date of the last modification and `CurrentDate` for the date of the conversion?

**Comment by GGillan** [comment]
"What do you think about the attribute-names ModificationDate for the date of the last modification and CurrentDate for the date of the conversion?"

Those would be great!

In the interim I found "Insert Date String" by Jakub Synowiec [https://marketplace.visualstudio.com/items?itemName=jsynowiec.vscode-insertdatestring&ssr=false#overview)](url) for a hot key to insert a date-time stamp. That made me think of two other aspects to the way I use MarkdownConverter.

Most of the time I actually want the time included with the date, because I often have multiple iterations on a single date and seeing the time helps me discard old printouts (often old printouts someone else has). I'm not sure if everyone who uses MarkdownConverter has a similar use case, so maybe if it were optional to include the time from whatever date attribute is used?

The other is that most of the time people have page numbers are at the bottom of the page, while a date (or date/time) is at the top. Not a major issue, just more of what people expect to see from convention. I haven't experimented with it yet or even looked at it, but when I get a chance I will probably see if I can reverse the header and footer options easily enough.

I notice the header currently also contains Author and Company (blank in the case of the files I've been working on), and my guess is those would usually be wanted in the same line as whichever date or date/time is used, but I might be wrong about other people's preferences. Easiest would be if the Settings for MarkdownConverter had check boxes for available items for "Header", "Footer", maybe even "Left", "Center", "Right". But as long as the documentation for MarkdownConverter had a list of available attributes and it was easy enough to edit which one went where, that would be fantastic.

I hope this is helpful for you, MarkdownConverter is certainly helpful for me!

Regards,
George

**Comment by manuth** [comment]
Alright - these are some points other than the file modified date initially addressed. I'll create separate issues for that matter.
I hope I caught every point you addressed here - let me know if I'm missing something.

1. More specific way to format dates: #55
2. Reorder placement of header/footer items: #56
3. Simplify the way to specify headers and footers: #57

Let me know if there's something missing

**Comment by GGillan** [comment]
👍👍
