### ISSUE TITLE
Default tag remains with "useSystemStyles = false"

### ISSUE THREAD

**Issue by badchenn** [manuth/MarkdownConverter#6]
I noticed that one of the default tags remains in the html though the setting is set to 'false'

    <body>
        <article class="vscode-light markdown-body">
            <div class="container">
    <h1 id="continuous-integration-continuous-deployment-assessment-guide">

The tag `<article ...>` remains between the `<body>` and custom `<div>` tags.  A scan of the code may report issues as it is not valid html/css.

Any way to strip this when setting "useSystemStyles: false"?

Thanks

**Comment by manuth** [comment]
Hey - yes, ofc. this is possible.
But please stay patient, I have my final thesis during the next two weeks.
I don't guess I will remove the article tag since this is a [valid HTML-tag](https://www.w3schools.com/tags/tag_article.asp).

Thanks for using MarkdownConverter

~Manu

**Comment by manuth** [comment]
I changed the default template to
```html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
        {{{styles}}}
    </head>
    <body>
        <article>
            {{{content}}}
        </article>
    </body>
</html>
```

The `vscode-light`-part will only be included when enabling `useSystemStyles` (which is endabled by default).

You can adjust your configuration if you want to provide your own template-file as followed:

```json
{
    "markdownConverter.document": {
        "style": {
            "template": ".vscode\\MyTemplate.html"
        }
    }
}
```
