### ISSUE TITLE
How to set HTML title?

### ISSUE THREAD

**Issue by orschiro** [manuth/MarkdownConverter#63]
Hi @manuth ,

Thanks for this great extension!

Question: How do you set the (tab) title when converting to an HTML file?

**Comment by manuth** [comment]
Hello @orschiro 
Thanks for pointing this out. Currently the title of the HTML file isn't set automatically.
You could include the `<title>`-Tag in your markdown-file, though, this might look sorta crappy...?

I'll think of another way to determine a title automatically.

**Comment by orschiro** [comment]
Maybe the title can be set using the preface?

```
---
title: "My title"
---
```

**Comment by manuth** [comment]
Sorry for letting you wait
I'm working on it rn and cause of the current way MarkdownConverter works.
Stay tuned as I will fix this as soon as possible.

**Comment by orschiro** [comment]
No worries, thanks for the update!

**Comment by manuth** [comment]
In the next release, you'll be able to set the `<title>`-tag's content by adding a `Title`-attribute either in your settings or in the YAML-head of your markdown-file.

This issue will be fixed in the upcoming version!

Thanks for your patience

**Comment by orschiro** [comment]
Nice, thanks!
