### ISSUE TITLE
Mention the addition of a Table of Content in the Readme

### ISSUE THREAD

**Issue by RoneoOrg** [manuth/MarkdownConverter#68]
A table of content can be added in generated documents, where `[[toc]]` is inserted

It would be nice to add this info to the Readme

**Comment by RoneoOrg** [comment]
Additional information:

MarkdownConverter provides a setting called `markdownConverter.ParsermToc.Indicator` which can be set to a regular expression to replace with the toc.

The default is `\[\[\s*toc\s*\]\]`, which matches `[[toc]]` with any number of spaces in between (e.g. `[[ toc ]]`, `[[toc]]` etc.).

So basically you should make your `test.md` look like this:

```
# Summary
[[ toc ]]
```
[Source](https://github.com/manuth/MarkdownConverter/issues/67#issuecomment-789805193)

**Comment by redtux** [comment]
Hi, I can confirm that using `[[ toc ]]` is working fine, while TOCs created by Markdown All in One only work with HTML.

When generating a PDF, the TOC is printed with the links being removed. No idea whether this is to be considered a bug or a feature (intended behavior). In any case this too should be mentioned in the README.
