### ISSUE TITLE
wants to download chromium

### ISSUE THREAD

**Issue by tik9** [manuth/MarkdownConverter#74]
When I want to run your extension, it asks me to download `chromium`. But it is already installed. Can I point your extension to my `chromium` in `/usr/bin/chromium`?

**Comment by manuth** [comment]
Thanks for pointing this out!
As far as I remember, there is no such option but I'll make sure to have this implemented for the next version

Thanks for using MarkdownConverter 💫

**Comment by orgwem** [comment]
Would really love to see a way to specify already installed Chrome oder Chromium. I am behind a corporate firewall which disallows downloading Chromium. However, Chrome is already installed on my machine so I could use that instead.

**Comment by manuth** [comment]
That's a good input - iirc, puppeteer actually does allow you to specify a custom chromium path, so I should be able to implement this easily!

I'm starting to work on MarkdownConverter again once I caught up with all my other projects

**Comment by orgwem** [comment]
And that's good news! Currently I have to use the plugin "markdown-pdf" by yzane (https://github.com/yzane/vscode-markdown-pdf) as it allows for that exact feature via the setting "markdown-pdf.executablePath". However this plugin is meant for american users (e.g. date format Month/Day/Year) and I would prefer having more output control.

**Comment by manuth** [comment]
I'm planning to allow users to specify their own `ChromiumExecutablePath` in their settings.
This will disable `MarkdownConverter`s question on whether to download the `puppeteer-core`s Chrome-revision and will instead check whether a file exists at the location indicated by the `ChromiumExecutablePath`.
