### ISSUE TITLE
HTML Links to External Stylesheets

### ISSUE THREAD

**Issue by richardy706** [manuth/MarkdownConverter#75]
The HTML conversion works very well but the styles are in external stylesheets on the local computer.  Therefore the HTML does not render styles when transferred to another computer.  Is there a way to have the style rules embedded in the document?

Version: 3.1.2

**Comment by manuth** [comment]
Hello
Thanks for your interest in MarkdownConverter.
I'll have a closer look on how to handle style-sheets during the next few days.

Sorry for letting you wait for such a long time

**Comment by manuth** [comment]
I put some thoughts into this and came up with a concept for for improving the treatment of stylesheets and javascript-files.

I'm planning to add an option `StyleSheetBehavior` and `ScriptBehavior` (let me know if you guys can make up a more suitable name) where users can set the treatment of `Relative` files, `Absolute` files and `Link`s.

Users will be able to choose between `Link` (adding a reference to the file) or `Scrape`/`Embed` or `Include`? (copying the code of the corresponding file into the document) and `Default` (letting MarkdownConverter decide, which basically add a reference to all links and copy the source of all files into the document).

Additionally, the `StyleSheets` and `Scripts`-option will allow the user to override MarkdownConverters behavior - allowing you to gain control on MarkdownConverter's asset-treatment of each file.

Let me know if there is something I've missed or something I could improve regarding this concept.
