### ISSUE TITLE
Would be nice to have "Convert All" Option

### ISSUE THREAD

**Issue by coderNeos** [manuth/MarkdownConverter#8]
Hi there! Really nice extension, helped me a lot. Is it possible to make option that converts all files in working directory?

**Comment by manuth** [comment]
Hello, Neos
Now that I've holidays I just let it go through my mind and I'm not too sure how to realize it.
Actually I'd rather want to make an option to convert _all_ Markdown-files into a single PDF file but I wouldn't know how to realize it or how to call the options etc.
But... I guess at first I'll just do it as you said and provide an option which converts every single Markdown-file inside the current workspace to a PDF... I'll improve it later on :'D
Thanks for your suggestion!

~Manu

**Comment by manuth** [comment]
Hello @coderneos. I just attempted to implement the feature and found myself unable to determine what textdocuments the user has currently opened.  It also isn't possible to get all files from the vsc-workspace.  Unfortunately this means it's not possible to resolve your issue at this time. Please enquire again if you find some determine the text-documents to convert.

**Comment by coderNeos** [comment]
Thanks for reply, i'm sorry that I haven't replied last time, i was to busy
with my job, if i have spare time i'll try to solve this issue and create
pull request.
Best Wishes, Artiom.

2017-09-05 4:48 GMT+08:00 Manuel Thalmann <notifications@github.com>:

**Comment by manuth** [comment]
Hello, @coderNeos
I just noticed that VS-Code's got a new feature for enumerating all documents contained by a workspace.

Well... this means it's finally possible to add a `Convert All...`-option!
This feature definitely will be implemented in the next version.

Stay tuned
