### ISSUE TITLE
[New feature request] : Footnote

### ISSUE THREAD

**Issue by damgot** [manuth/MarkdownConverter#82]
Hello,

The extended markdown syntax include footnote (with the syntax  [^1]). Is it possible to have this feature with MarkdownConverter for pdf generation ?

thanks

**Comment by manuth** [comment]
Head over to the marketplace and install the "Markdown Footnote" extension:
https://marketplace.visualstudio.com/items?itemName=houkanshan.vscode-markdown-footnote

Make sure, that the system-parser is enabled (`markdownConverter.Parser.SystemParserEnabled`).
Having this setting enabled and the extension mentioned before installed, your conversion output will include footnotes.

**Comment by manuth** [comment]
Please let me know whether this worked for you

**Comment by Postur** [comment]
> Head over to the marketplace and install the "Markdown Footnote" extension: https://marketplace.visualstudio.com/items?itemName=houkanshan.vscode-markdown-footnote
> 
> Make sure, that the system-parser is enabled (`markdownConverter.Parser.SystemParserEnabled`). Having this setting enabled and the extension mentioned before installed, your conversion output will include footnotes.

This extension works more like endnotes.

1. Footnotes appear on the bottom of the page that contains the sentence to which it refers.
2. Endnotes are listed at the end of the paper on separate pages.

Integrating this would involve changing the footer for each page in puppeteer, I guess.

but as endnotes it works perfectly.

**Comment by manuth** [comment]
Thanks for pointing this out!
I do agree, that this isn't quite the same thing like a footnote. However, puppeteer doesn't support setting different footers for individual pages and I don't know of a CSS feature which would be able to add content to the end of a page.

In hope that the Markdown Footnote plug-in will work out for you guys, I'll close this issue.

Feel free to open it back up or discuss this topic further in this issue.
